# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
