# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190713_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
