# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0005_orderedbook_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookstore_orderedbook_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
