# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_orderedbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
