# Generated by Django 2.2.3 on 2019-07-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank='false', upload_to='books_images/'),
        ),
    ]
