# Generated by Django 2.2.3 on 2019-07-28 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20190728_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
