# Generated by Django 2.2.3 on 2019-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_order_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percentage',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
